import asyncio
import csv
import os
import sys
import time
import logging
from datetime import datetime
from pathlib import Path

import httpx
import yaml

MAX_PAIRS         = min(int(os.getenv("MAX_PAIRS",          "32")), 32)
N_QUBITS          = int(os.getenv("N_QUBITS",               "1024"))
BATCH_SIZE        = int(os.getenv("BATCH_SIZE",             "10"))
POLL_INTERVAL_S   = float(os.getenv("POLL_INTERVAL_S",      "5"))
SESSION_TIMEOUT_S = float(os.getenv("SESSION_TIMEOUT_S",    "1800"))
MEMORY_WARN_GB    = float(os.getenv("MEMORY_WARN_GB",       "8"))
KME_URL           = os.getenv("KME_URL",   "http://localhost:8000")
NETWORK_YAML      = Path(os.getenv("NETWORK_YAML", "nodes/network.yaml"))
RESULTS_DIR       = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
)
logger = logging.getLogger("test_scalability_32")

CSV_FIELDS = [
    "pair", "alice_label", "bob_label", "qkdl_url",
    "session_id", "start_error", "status",
    "n_qubits", "n_delivered", "n_sifted",
    "qber", "key_len", "elapsed_s", "error_message", "intercepted",
]


def pair_ports(n: int) -> tuple[int, int, int]:
    if n < 1 or n > 32:
        raise ValueError(f"Pair number must be 1–32, got {n}")
    alice = 8001        if n == 1 else 8100 + n
    bob   = 8002        if n == 1 else 8200 + n
    qkdl  = (8003 + (n - 1) * 10) if n <= 8 else (9003 + (n - 9) * 10)
    return alice, bob, qkdl


def pair_info(n: int) -> dict:
    alice_p, bob_p, qkdl_p = pair_ports(n)
    return {
        "pair":        n,
        "alice_label": f"alice-{n}",
        "alice_url":   f"http://localhost:{alice_p}",
        "bob_label":   f"bob-{n}",
        "qkdl_url":    f"http://localhost:{qkdl_p}",
        "alice_port":  alice_p,
        "bob_port":    bob_p,
        "qkdl_port":   qkdl_p,
    }


def _pair_yaml_block(n: int) -> list[str]:
    alice_p, bob_p, qkdl_p = pair_ports(n)
    alice_url = f"http://localhost:{alice_p}"
    bob_url   = f"http://localhost:{bob_p}"
    qkdl_url  = f"http://localhost:{qkdl_p}"
    return [
        f"  # Pair {n}: alice-{n} <-> bob-{n}  QKDL :{qkdl_p}",
        f"  - label:   alice-{n}",
        f"    role:    sender",
        f"    module:  nodes.alice.main",
        f"    port:    {alice_p}",
        f"    env:",
        f"      ALICE_LABEL: alice-{n}",
        f'      ALICE_URL:   "{alice_url}"',
        f"      BATCH_SIZE:  \"10\"",
        f'      QKDL_URL:    "{qkdl_url}"',
        f"",
        f"  - label:   bob-{n}",
        f"    role:    receiver",
        f"    module:  nodes.bob.main",
        f"    port:    {bob_p}",
        f"    env:",
        f"      BOB_LABEL: bob-{n}",
        f'      BOB_URL:   "{bob_url}"',
        f'      QKDL_URL:  "{qkdl_url}"',
        f"",
    ]


def generate_network_yaml(n_pairs: int) -> str:
    lines = [
        "# Auto-generated by test_scalability_32.py",
        "# Edit MAX_PAIRS and re-run the test to regenerate.",
        "#",
        "# Launch order:",
        "#   1. Redis           (already running)",
        "#   2. node_runner     (launches QKDLs, KME, nodes)",
        "#   3. Sifting worker  (start once, shared):",
        "#",
        "#      celery -A workers.celery_config worker \\",
        "#             --queues=sifting --concurrency=1 --loglevel=info -n sifting@%h",
        "#",
        "# Per-session qubit workers are managed automatically by Alice nodes.",
        "",
        "kme:",
        '  url: "http://localhost:8000"',
        "  key_ttl_seconds: 600",
        "",
        "qkdl:",
        '  url: "http://localhost:8003"',
        "",
        "nodes:",
        "",
    ]
    for n in range(1, n_pairs + 1):
        lines.extend(_pair_yaml_block(n))

    lines += [
        "  # Eve — one instance, role=monitor",
        "  - label:   eve-1",
        "    role:    monitor",
        "    module:  nodes.eve.main",
        "    port:    8010",
        "    env:",
        "      EVE_LABEL: eve-1",
        '      EVE_URL:   "http://localhost:8010"',
        "",
    ]
    return "\n".join(lines)


def sync_network_yaml(n_pairs: int, yaml_path: Path) -> bool:
    new_content = generate_network_yaml(n_pairs)

    # Count existing sender nodes in the current file
    existing_pairs = 0
    if yaml_path.exists():
        try:
            with open(yaml_path) as f:
                cfg = yaml.safe_load(f)
            existing_pairs = sum(
                1 for node in cfg.get("nodes", [])
                if node.get("role") == "sender"
            )
        except Exception:
            pass

    if existing_pairs == n_pairs:
        logger.info(
            f"network.yaml already has {n_pairs} pairs — no change needed"
        )
        return False

    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(new_content)
    logger.info(
        f"network.yaml written: {existing_pairs} → {n_pairs} pairs  ({yaml_path})"
    )
    return True


def estimate_ram_gb(n: int) -> float:
    # QKDL ~180 MB, Alice ~60 MB, Bob ~60 MB, per-session worker ~90 MB
    return n * (0.18 + 0.06 + 0.06 + 0.09) + 0.2


async def check_alice_ready(client: httpx.AsyncClient, url: str) -> bool:
    try:
        r = await client.get(f"{url}/health", timeout=3.0)
        return r.status_code == 200
    except Exception:
        return False


async def wait_for_nodes(pairs: list[dict], timeout: float = 60.0) -> None:
    deadline = time.time() + timeout
    async with httpx.AsyncClient() as client:
        while time.time() < deadline:
            results = await asyncio.gather(
                *[check_alice_ready(client, p["alice_url"]) for p in pairs],
                return_exceptions=True,
            )
            ready = sum(1 for r in results if r is True)
            if ready == len(pairs):
                logger.info(f"All {len(pairs)} alice nodes ready")
                return
            not_ready = [
                pairs[i]["alice_label"]
                for i, r in enumerate(results) if r is not True
            ]
            logger.info(
                f"Waiting for nodes … {ready}/{len(pairs)} ready "
                f"(not ready: {not_ready[:5]}{'…' if len(not_ready)>5 else ''})"
            )
            await asyncio.sleep(3.0)
    raise TimeoutError(
        f"Only {ready}/{len(pairs)} alice nodes came up within {timeout}s. "
        f"Did you restart node_runner after network.yaml changed?"
    )

async def start_session(
    client:     httpx.AsyncClient,
    pair:       dict,
    n_qubits:   int,
    batch_size: int,
) -> dict:
    url = (
        f"{pair['alice_url']}/start"
        f"?receiver_label={pair['bob_label']}"
        f"&n_qubits={n_qubits}"
        f"&batch_size={batch_size}"
    )
    try:
        r = await client.post(url, timeout=20.0)
        r.raise_for_status()
        body = r.json()
        logger.info(
            f"[pair {pair['pair']:2d}] started  id={body['session_id'][:8]}"
        )
        return {**pair, "session_id": body["session_id"],
                "start_error": None}
    except Exception as e:
        logger.error(f"[pair {pair['pair']:2d}] /start failed: {e}")
        return {**pair, "session_id": None, "start_error": str(e)}


async def poll_session(client: httpx.AsyncClient, sid: str) -> dict:
    try:
        r = await client.get(f"{KME_URL}/sessions/{sid}", timeout=10.0)
        r.raise_for_status()
        return r.json()
    except Exception:
        return {}


def build_row(rec: dict, kme: dict, n_qubits: int, fallback_elapsed: float) -> dict:
    sid = rec.get("session_id")
    return {
        "pair":          rec["pair"],
        "alice_label":   rec["alice_label"],
        "bob_label":     rec["bob_label"],
        "qkdl_url":      rec["qkdl_url"],
        "session_id":    sid or "FAILED_TO_START",
        "start_error":   rec.get("start_error") or "",
        "status":        kme.get("status", "not_started"),
        "n_qubits":      kme.get("n_qubits", n_qubits),
        "n_delivered":   kme.get("n_delivered", 0),
        "n_sifted":      kme.get("n_sifted", 0),
        "qber":          round(kme.get("qber", 0.0), 6),
        "key_len":       len(kme.get("key_final", "")),
        "elapsed_s":     kme.get("elapsed_s", round(fallback_elapsed, 2)),
        "error_message": kme.get("error_message", ""),
        "intercepted":   kme.get("intercepted", False),
    }

async def run_test(
    pairs:      list[dict],
    n_qubits:   int,
    batch_size: int,
    csv_writer: csv.DictWriter,
    csv_fh,
) -> list[dict]:

    logger.info(
        f"\n{'='*60}\n"
        f"  {len(pairs)} pairs | {n_qubits} qubits | batch={batch_size}\n"
        f"{'='*60}"
    )

    await wait_for_nodes(pairs)
    wall_start = time.time()

    logger.info(f"Launching {len(pairs)} sessions simultaneously …")
    async with httpx.AsyncClient(timeout=30.0) as client:
        session_records = await asyncio.gather(
            *[start_session(client, p, n_qubits, batch_size) for p in pairs]
        )

    started = [r for r in session_records if r["session_id"] is not None]
    failed  = [r for r in session_records if r["session_id"] is None]
    logger.info(
        f"Launched: {len(started)}  failed to start: {len(failed)}"
    )

    all_rows: list[dict] = []
    for rec in failed:
        row = build_row(rec, {}, n_qubits, 0)
        csv_writer.writerow(row)
        all_rows.append(row)
    csv_fh.flush()

    terminal = {"done", "aborted"}
    finished: dict[str, dict] = {}

    async with httpx.AsyncClient(timeout=30.0) as client:
        while True:
            pending = [r for r in started if r["session_id"] not in finished]
            if not pending:
                break

            wall_elapsed = time.time() - wall_start
            if wall_elapsed > SESSION_TIMEOUT_S:
                logger.error(
                    f"Hard timeout ({SESSION_TIMEOUT_S}s): "
                    f"{len(pending)} sessions still pending"
                )
                for rec in pending:
                    sid = rec["session_id"]
                    kme = {"status": "timeout",
                           "error_message": f"timed out after {wall_elapsed:.0f}s"}
                    finished[sid] = kme
                    row = build_row(rec, kme, n_qubits, wall_elapsed)
                    csv_writer.writerow(row)
                    all_rows.append(row)
                csv_fh.flush()
                break

            polls = await asyncio.gather(
                *[poll_session(client, r["session_id"]) for r in pending]
            )

            newly_done = 0
            for rec, kme in zip(pending, polls):
                sid = rec["session_id"]
                if kme.get("status") in terminal:
                    finished[sid] = kme
                    newly_done += 1
                    row = build_row(
                        rec, kme, n_qubits, time.time() - wall_start
                    )
                    csv_writer.writerow(row)   # written immediately
                    csv_fh.flush()
                    all_rows.append(row)
                    logger.info(
                        f"[pair {rec['pair']:2d}] "
                        f"{kme['status'].upper():7s}  "
                        f"elapsed={kme.get('elapsed_s', 0):.1f}s  "
                        f"sifted={kme.get('n_sifted', 0)}  "
                        f"qber={kme.get('qber', 0)*100:.2f}%  "
                        f"key={len(kme.get('key_final', ''))}"
                    )

            remaining = len(pending) - newly_done
            if remaining:
                logger.info(
                    f"  … {remaining} running "
                    f"(wall={time.time()-wall_start:.0f}s  "
                    f"done={len(finished)}/{len(started)})"
                )

            await asyncio.sleep(POLL_INTERVAL_S)

    wall_elapsed = time.time() - wall_start

    n_done    = sum(1 for r in all_rows if r["status"] == "done")
    n_aborted = sum(1 for r in all_rows if r["status"] == "aborted")
    n_timeout = sum(1 for r in all_rows if r["status"] == "timeout")
    e_vals    = [r["elapsed_s"] for r in all_rows if r["status"] == "done"]

    logger.info(
        f"\n{'='*60}\n"
        f"  RESULTS  ({len(pairs)} pairs | {n_qubits} qubits)\n"
        f"{'='*60}\n"
        f"  Wall clock : {wall_elapsed:.1f}s\n"
        f"  Done       : {n_done}/{len(pairs)}\n"
        f"  Aborted    : {n_aborted}\n"
        f"  Timed out  : {n_timeout}\n"
        + (
            f"  Elapsed    : min={min(e_vals):.1f}s  "
            f"avg={sum(e_vals)/len(e_vals):.1f}s  "
            f"max={max(e_vals):.1f}s\n"
            if e_vals else ""
        )
        + f"{'='*60}"
    )

    print("\nPair | Alice    | Status  | Elapsed  | n_sifted | QBER   | KeyLen")
    print("-" * 72)
    for r in sorted(all_rows, key=lambda x: x["pair"]):
        print(
            f"  {r['pair']:2d} | {r['alice_label']:<8} | "
            f"{r['status']:<7} | {r['elapsed_s']:8.1f}s | "
            f"{r['n_sifted']:8d} | "
            f"{r['qber']*100:5.2f}% | {r['key_len']}"
        )

    return all_rows

async def main() -> int:
    logger.info(
        f"MAX_PAIRS={MAX_PAIRS}  N_QUBITS={N_QUBITS}  "
        f"BATCH_SIZE={BATCH_SIZE}"
    )

    yaml_changed = sync_network_yaml(MAX_PAIRS, NETWORK_YAML)
    if yaml_changed:
        logger.warning(
            "\n"
            "  network.yaml was updated.\n"
            "  Please restart node_runner (and wait for all nodes to start)\n"
            "  before re-running this test:\n"
            "\n"
            "    python node/node_runner.py --with-kme\n"
            "\n"
            "  Then run the test again."
        )
        return 2  

    est = estimate_ram_gb(MAX_PAIRS)
    if est > MEMORY_WARN_GB:
        logger.warning(
            f"Estimated RAM for {MAX_PAIRS} pairs: ~{est:.1f} GB "
            f"(threshold {MEMORY_WARN_GB} GB). "
            f"Increase WSL memory or reduce MAX_PAIRS if you see crashes. "
            f"See README for .wslconfig instructions."
        )
    else:
        logger.info(f"Estimated RAM: ~{est:.1f} GB — OK")

    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            r = await client.get(f"{KME_URL}/health")
            r.raise_for_status()
        logger.info("KME healthy")
    except Exception as e:
        logger.error(f"KME not reachable at {KME_URL}: {e}")
        return 1

    pairs = [pair_info(n) for n in range(1, MAX_PAIRS + 1)]

    ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_path = RESULTS_DIR / f"scalability_{MAX_PAIRS}pairs_{N_QUBITS}q_{ts}.csv"
    fh       = open(csv_path, "w", newline="")
    writer   = csv.DictWriter(fh, fieldnames=CSV_FIELDS)
    writer.writeheader()
    fh.flush()
    logger.info(f"Results → {csv_path}  (written incrementally)")

    try:
        rows = await run_test(pairs, N_QUBITS, BATCH_SIZE, writer, fh)
    finally:
        fh.close()
        logger.info(f"CSV closed → {csv_path}")

    n_done = sum(1 for r in rows if r["status"] == "done")
    return 0 if n_done == len(pairs) else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
